### ISSUE TITLE
NVDA 2019.3 Compatibility

### ISSUE THREAD

**Issue by smeveriss** [nstockton/nvda-add-ons#1]
Hi, What is the status of compatability between all addons for nvda 2019.3 in particular the interactive fiction one but of course it relates to all others.
Will these be updated?
Shaun

**Comment by nstockton** [comment]
Currently all add-ons in this repository have been updated for NVDA 2019.3, except for the BTSync, JMC, and Radegast add-ons. I will update JMC, but I don't plan on updating BTSync or Radegast.

**Comment by alex19EP** [comment]
hello. Are you interested in publishing addons on the official website?

**Comment by nstockton** [comment]
I believe an old version of the MushClient add-on and an old version of the mIRC enhancements add-on are on there, but I don't think I was ever given the ability to update them. I think the two add-ons that people have been most interested in are the MushClient and IF Interpreters add-ons.

**Comment by alex19EP** [comment]
> I think the two add-ons that people have been most interested in are the MushClient and IF  > Interpreters add-ons.

yep. for me it so.

maybe you should write to the nvda-addon-list.

**Comment by nstockton** [comment]
The JMC add-on has been updated for NVDA 2019.3, and I have placed read me files in the BTSync and Radegast directories to reflect that they are no longer being updated by me.
