### ISSUE TITLE
Why is new text in a line only considered when the change is only 2 characters?

### ISSUE THREAD

**Issue by sukiletxe** [nstockton/nvda-add-ons#2]
Alright, first, sorry for the weird title.

Some Spanish text adventures, particularly in narrative sequences or hints, use the technique where the last line is typed as it goes or in chunks (think of the former as a typewriter, the latter as sentences or parts of sentences coming in chunks). If you want examples of the latter (I can't test the former now, sorry), [here is one example](https://1drv.ms/u/s!AoR_kDEmAgXSisUeutks9g6LKhVwoA?e=OsPt99) (press i after it starts).

From the source, I can see that only the difference is taken into account (and thus spoken instead of the whole line) when it is less than 2 characters, and that it was set originally to 15. I tried setting it to a large number (200) and it worked just fine for this use case.

So why is it set to 2?

Thanks!

**Comment by nstockton** [comment]
If I remember correctly, the reason had to do with certain prompts failing to be spoken. It's been around 8 years now and I made this add-on before I started using source code revision control, so sadly I can't refer back to see the exact reason.
