### ISSUE TITLE
winfrotz and winglulxe latest versions don't seem to be compatible with the addons

### ISSUE THREAD

**Issue by smeveriss** [nstockton/nvda-add-ons#3]
Hi.
Latest winfrotz 1.22 and glulxe 0.5 releases no longer work with the if interpreters addon.

**Comment by kara-louise** [comment]
I have also noticed this.

**Comment by Mohamed00** [comment]
Here's the last version of Frotz that worked with the addon. http://web.archive.org/web/20191009130728if_/https://www.ifarchive.org/if-archive/infocom/interpreters/frotz/WindowsFrotzInstaller.exe

**Comment by smeveriss** [comment]
Well it would be good if frotz and glulxe latest versions worked.

In addition nvda 2021.1 needs this thing to be updated and the 2021.2 release needs more work done.
So its really essential for someone to get the frotz and glulxe stuff fixed else this thing is going to become useless

**Comment by nstockton** [comment]
The add-on has been updated to support the latest versions of Windows Frotz and Windows Glulxe, and to add support for NVDA 2021.1.
The reason why the latest versions of Frotz and Glulxe stopped working with the add-on is because the window class names for both of them changed, most likely due to the program author using a newer compiler.

**Comment by smeveriss** [comment]
The versions of these are

glulxe 0.5.4.151
frotz 1.22
And while yeah the new nvda stuff is working, these still do not work.
Also on a side note while I can recompile the addons myself it would be nice to have all the compatible ones on releases and  have this stuff pulled for the nvda addons site especially since this stuff has been round for ages.

**Comment by nstockton** [comment]
I have made the add-on less strict when searching for the window class name. Let me know if it now works for you.
Tested with Glulxe 0.5.4 and Frotz 1.22.
I will look into what is involved in uploading an add-on to the official repository.

**Comment by kara-louise** [comment]
As far as I can tell after a quick test, the add-on now works with both interpreters.

**Comment by nstockton** [comment]
Awesome, if the change fixes the issue for @smeveriss as well, I'll close this.
