### ISSUE TITLE
Compatibility with upcoming NVDA version 2022.1

### ISSUE THREAD

**Issue by kara-louise** [nstockton/nvda-add-ons#4]
Will your add-ons (particularly the IF Interpreters one) be compatible with the next version of NVDA? It appears to be one of their add-on breaking releases, which I believe is going to be an annual thing.

**Comment by nstockton** [comment]
I updated the manifest files for the add-ons. That was all that was required for the latest NVDA update in this case.

**Comment by jmdaweb** [comment]
Hi,
Do you host packaged versions of these add-ons somewhere? It would be interesting to link them from the nvda-addons.org website.
