### ISSUE TITLE
Submitting your add-ons to the official Add-on directory

### ISSUE THREAD

**Issue by kara-louise** [nstockton/nvda-add-ons#5]
Bringing this up again as I saw a tweet that explains how you go about submitting your add-ons.

https://twitter.com/joslee/status/1488630752983928832

**Comment by nstockton** [comment]
The IF Interpreters add-on is now maintained by Noelia Ruiz Martínez and can be found here https://github.com/nvdaes/ifInterpreters. I believe that Noelia has submitted the add-on to the add-on store.
